---
name: actionlint with reviewdog

on:
  pull_request:
    paths:
      - ".github/workflows/**"

jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: reviewdog/action-actionlint@v1.27.0
