---
name: renovate config validate

on:
  pull_request:
    paths:
      - renovate.json

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: rinchsan/renovate-config-validator@v0.0.12
        with:
          pattern: "renovate.json"
