---
name: textlint with reviewdog

on:
  pull_request:
    paths:
      - 'src/work.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  textlint:
    permissions:
      checks: write
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Use Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "18"
      - run: yarn install
      - uses: reviewdog/action-setup@154bb4214db7d87bdb814a346ec67b3472fe1c5f # v1.1.0
        with:
          reviewdog_version: latest
      - name: textlint work.md
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx textlint -f checkstyle "./src/work.md" | \
          reviewdog -f=checkstyle -name="textlint" -reporter=github-pr-review -diff="git diff ${{ github.event.pull_request.base.ref }}"
