---
name: textlint with reviewdog

on:
  pull_request:
    paths:
      - 'src/work.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  textlint:
    permissions:
      checks: write
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Use Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: "18"
      - run: yarn install
      - uses: reviewdog/action-setup@80a06617492b461a66508e2dedf16233f0506804 # v1.0.6
        with:
          reviewdog_version: latest
      - name: textlint work.md
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx textlint -f checkstyle "./src/work.md" | \
          reviewdog -f=checkstyle -name="textlint" -reporter=github-pr-review -diff="git diff ${{ github.event.pull_request.base.ref }}"
