---
name: yamllint

on:
  pull_request:
    paths:
      - "**.ya?ml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Run yamllint with reviewdog
        uses: reviewdog/action-yamllint@722e651555c5ca6db0edaada08e049825f74e431 # v1.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
