---
name: yamllint

on:
  pull_request:
    paths:
      - "**.ya?ml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Run yamllint with reviewdog
        uses: reviewdog/action-yamllint@b00d2ab43a360f25846817aa225d3b39001affc3 # v1.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
